### ISSUE TITLE
[1.12.2/1.6.4a-G] Crash on loading world

### ISSUE THREAD

**Issue by LukeTech2006** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#192]
When loading a HBM-Powered World, I recieve this:

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/8/22 5:28 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.hbm.tileentity.machine.TileEntityMachineRadar.entityJoinWorld(TileEntityMachineRadar.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_101_TileEntityMachineRadar_entityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.WorldServer.func_175650_b(WorldServer.java:1065)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:860)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:561)
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:70)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_142_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:976)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251)
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:151)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4504102160 bytes (4295 MB) / 6576668672 bytes (6272 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 16, tcache: 1, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_G5 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version             | Source                                         | Signature                                |
	|:------ |:----------------------- |:------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2              | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                     | 9.42                | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                     | 8.0.99.99           | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | forge                   | 14.23.5.2847        | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | opencomputers|core      | 1.7.5.192           | minecraft.jar                                  | None                                     |
	| LCHIJA | crafttweaker            | 4.1.20              | CraftTweaker2-1.12-4.1.20.666.jar              | None                                     |
	| LCHIJA | jei                     | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJA | quark                   | r1.6-179            | Quark-r1.6-179.jar                             | None                                     |
	| LCHIJA | autoreglib              | 1.3-32              | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCHIJA | biomesoplenty           | 7.0.1.2444          | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar  | None                                     |
	| LCHIJA | blockcraftery           | 1.12.2-1.3.1        | blockcraftery-1.12.2-1.3.1.jar                 | None                                     |
	| LCHIJA | cameraobscura           | 0.0.1               | CameraObscura-1.0.3.jar                        | None                                     |
	| LCHIJA | cctweaked               | 1.89.2              | cc-tweaked-1.12.2-1.89.2.jar                   | None                                     |
	| LCHIJA | computercraft           | 1.89.2              | cc-tweaked-1.12.2-1.89.2.jar                   | None                                     |
	| LCHIJA | cd4017be_lib            | 6.5.1               | CD4017BE_lib-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-1.0.2.45   | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux            | 2.1.1               | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCHIJA | cofhcore                | 4.6.6               | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCHIJA | cofhworld               | 1.4.0               | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCHIJA | ctgui                   | 1.0.0               | CraftTweaker2-1.12-4.1.20.666.jar              | None                                     |
	| LCHIJA | crafttweakerjei         | 2.0.3               | CraftTweaker2-1.12-4.1.20.666.jar              | None                                     |
	| LCHIJA | dynamictrees            | 1.12.2-0.9.25       | DynamicTrees-1.12.2-0.9.25.jar                 | None                                     |
	| LCHIJA | energyconverters        | 1.3.7.30            | energyconverters_1.12.2-1.3.7.30.jar           | None                                     |
	| LCHIJA | opencomputers           | 1.7.5.192           | OpenComputers-MC1.12.2-1.7.5.192.jar           | None                                     |
	| LCHIJA | zerocore                | 1.12.2-0.1.2.9      | zerocore-1.12.2-0.1.2.9.jar                    | None                                     |
	| LCHIJA | bigreactors             | 1.12.2-0.4.5.68     | ExtremeReactors-1.12.2-0.4.5.68.jar            | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.2.83            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.2.83            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.2.83            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
	| LCHIJA | hbm                     | hbm-1.6.4.1A-1.12.2 | hbm-1.6.4a-Gv1.jar                             | None                                     |
	| LCHIJA | ic2                     | 2.8.170-ex112       | industrialcraft-2-2.8.170-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | journeymap              | 1.12.2-5.7.1        | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCHIJA | mcjtylib_ng             | 3.5.4               | mcjtylib-1.12-3.5.4.jar                        | None                                     |
	| LCHIJA | theoneprobe             | 1.4.28              | theoneprobe-1.12-1.4.28.jar                    | None                                     |
	| LCHIJA | thermalfoundation       | 2.6.7               | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCHIJA | immersiveengineering    | 0.12-98             | ImmersiveEngineering-0.12-98.jar               | None                                     |
	| LCHIJA | immersivetech           | 1.9.97              | MCTImmersiveTechnology-1.12.2-1.9.97.jar       | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.4.43            | MrTJPCore-1.12.2-2.1.4.43-universal.jar        | None                                     |
	| LCHIJA | patchouli               | 1.0-23.6            | Patchouli-1.0-23.6.jar                         | None                                     |
	| LCHIJA | projectred-core         | 4.9.4.120           | ProjectRed-1.12.2-4.9.4.120-Base.jar           | None                                     |
	| LCHIJA | projectred-compat       | 1.0                 | ProjectRed-1.12.2-4.9.4.120-compat.jar         | None                                     |
	| LCHIJA | projectred-integration  | 4.9.4.120           | ProjectRed-1.12.2-4.9.4.120-integration.jar    | None                                     |
	| LCHIJA | projectred-transmission | 4.9.4.120           | ProjectRed-1.12.2-4.9.4.120-integration.jar    | None                                     |
	| LCHIJA | projectred-illumination | 4.9.4.120           | ProjectRed-1.12.2-4.9.4.120-lighting.jar       | None                                     |
	| LCHIJA | ptrmodellib             | 1.0.5               | PTRLib-1.0.5.jar                               | None                                     |
	| LCHIJA | rs_ctr                  | 0.3.1               | RedstoneControl-1.12.2-0.3.1.3.jar             | None                                     |
	| LCHIJA | rftools                 | 7.73                | rftools-1.12-7.73.jar                          | None                                     |
	| LCHIJA | sgcraft                 | 2.0.3               | SGCraft-2.0.4-bugfix-1.jar                     | None                                     |
	| LCHIJA | thermaldynamics         | 2.5.6               | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None                                     |
	| LCHIJA | worldedit               | 6.1.10              | worldedit-forge-mc1.12.2-6.1.10-dist.jar       | None                                     |
	| LCHIJA | mysticallib             | 1.12.2-1.13.0       | mysticallib-1.12.2-1.13.0.jar                  | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14742 Compatibility Profile Context 21.7.2 27.20.22021.1002
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8`

**Comment by Drillgon200** [comment]
Fixed.

**Comment by LukeTech2006** [comment]
thank you, we'll try

**Comment by Flouffy** [comment]
> Fixed.

Not fixed x) I still have the problem with the latest HBM version
