### ISSUE TITLE
HBM's Nuclear Tech Mod with other mod conflict?

### ISSUE THREAD

**Issue by ghost** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#51]
[debug-2.log](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/5985708/debug-2.log)
here's debug log
Always stop at Draconic Evolution's Loading Hard Mode Recipe...
But deleting HBM's Nuclear Tech Mod can solve,
Can you help me see what happened? thanks.
(Sorry my english is not very good...)

**Comment by Drillgon200** [comment]
Could you try disabling 1.28_enableRecipes in the config to see if that's what's causing the issue?

**Comment by ghost** [comment]
I'm disabled 1.28_enableRecipes in the config, the problem is solved, but the recipe will disappear

**Comment by ghost** [comment]
> Could you try disabling 1.28_enableRecipes in the config to see if that's what's causing the issue?

Yes

**Comment by Drillgon200** [comment]
I still have absolutely no clue what the problem is with registering recipes like that.

**Comment by Drillgon200** [comment]
Looks like draconic does the same in code registration I do, I'll have to test more later.

**Comment by Drillgon200** [comment]
Why does this have to only happen with massive packs that take 3 ages to load and debug.

**Comment by Drillgon200** [comment]
Ok now I can't even replicate the issue I had with another pack. Can you possibly provide your pack? I doubt I can replicate this bug without it.

**Comment by Drillgon200** [comment]
Some new information leads me to believe that it was thousands of fluid duct recipes being registered under increasingly long name causing this. It's untested, but this may be fixed in the next update.
